default: &default
  adapter: postgresql
  encoding: unicode
  username: ubuntu

  pool: 5

development:
  <<: *default
  database: Ideas_development

test:
  <<: *default
  database: Ideas_test


production:
  <<: *default
  database: Ideas_production
  password: <%= ENV['IDEAS_DATABASE_PASSWORD'] %>
